local ffi=require('ffi')
local native=ffi.load(G60_FIXTURE_DLL)
local Allowlist=require('g60.target_allowlist')
local Priority=require('g60.native_priority')
local passed=0
local function test(name,fn) fn();passed=passed+1;print('PASS '..name) end
local function setup()
    local f=G60PriorityWindows.setup()
    f.target_allowed=Allowlist.new({resource='9e2e17f2ccccafdd'},G60WeakpointWindows.profiles)
    f.select(0);f.candidate(1,521,100);f.candidate(2,522,10);f.candidate(3,523,5);f.candidate(4,524,1)
    f.ping(0,522,600,2);f.ping(1,523,600,1);f.ping(2,524,600,0)
    return f
end
local function ids(mark)
    local out={};for _,m in ipairs(mark and mark.queue or {}) do out[#out+1]=tostring(m.id) end;return table.concat(out,',')
end
test('latest C then older B then A outrank unmarked Titan, including after visible mark expiry',function()
    local f=setup();local mark=f.pings:observe();assert(ids(mark)=='524,523,522')
    local r=f.step(nil,mark);assert(r.track.id==524 and r.selected_mark_index==1 and r.mark_queue_count==3)
    for slot=0,2 do f.float(f.ring+16+slot*0x58,0x14,11) end
    mark=f.pings:observe();assert(ids(mark)=='524,523,522' and not mark.current)
    native.fixture_dead(524);r=f.step(nil,mark)
    assert(r.track.id==523 and r.selected_mark_index==2 and r.selected_mark_id==523 and r.reason=='REMEMBERED_PING')
    mark=f.pings:observe();assert(ids(mark)=='523,522')
    f.u32(f.candidates,0x310,3);native.fixture_dead(523);r=f.step(nil,mark)
    assert(r.track.id==522 and r.reason=='REMEMBERED_PING')
    assert(ids(f.pings:observe())=='522' and native.fixture_bad_args()==0)
end)
test('newest missing from candidates uses older mark before automatic priority and preserves newest memory',function()
    local f=setup();f.u32(f.candidates,0x310,3)
    local mark=f.pings:observe();local r=f.step(nil,mark)
    assert(r.track.id==523 and r.selected_mark_index==2 and r.mark_candidate_observed==false)
    assert(ids(f.pings:observe())=='524,523,522')
    f.candidate(4,524,1);assert(f.step(nil,f.pings:observe()).track.id==524)
end)
test('re-mark older A moves it ahead for new acquisitions while a valid existing C lock persists',function()
    local f=setup();local first=f.step(nil,f.pings:observe())
    f.ping(3,522);local mark=f.pings:observe();assert(ids(mark)=='522,524,523')
    assert(f.step(first.track,mark).track.id==524)
    local new=f.step(nil,mark);assert(new.track.id==522 and new.selected_mark_index==1)
end)
test('forbidden Commander and teammate marks cannot displace local whitelisted history',function()
    local f=setup();f.pings:observe()
    f.ping(3,526,600,0);f.ping(4,521,601,0)
    local mark=f.pings:observe();assert(ids(mark)=='524,523,522')
    assert(f.step(nil,mark).track.id==524)
end)
test('recycled newest Unit removes only that mark and leaves older valid marks usable',function()
    local f=setup();f.pings:observe();f.generations[4]=1
    local mark,why=f.pings:observe();assert(ids(mark)=='523,522',tostring(why))
    assert(f.step(nil,mark).track.id==523)
end)
test('ring wrap and equal ages still prioritize the last local ring entry',function()
    local f=setup();f.pings:reset();f.u32(f.ring,8,126)
    f.ping(126,522);f.ping(127,523);f.ping(0,524)
    local mark=f.pings:observe();assert(ids(mark)=='524,523,522')
    assert(f.step(nil,mark).track.id==524)
end)
test('independent new acquisitions may share a marked target; there is no one-grenade reservation',function()
    local f=setup();local mark=f.pings:observe();local first=f.step(nil,mark)
    local second,why=Priority.new(f):step(f.scope(),nil,mark)
    assert(second,why);assert(first.track.id==524 and second.track.id==524)
end)
test('runtime observes multi-mark history before a grenade exists and skips missing latest candidate',function()
    local key='1a7fcdff98c664b0';local f=G60WeakpointWindows.setup(key,G60WeakpointWindows.profiles[key],true)
    f.candidate(2,521,100)
    f.ping(0,522,600,1);f.ping(1,524,600,0)
    f.present=false;f.host:tick();assert(native.fixture_points()==0)
    f.float(f.ring+16,0x14,11);f.float(f.ring+16+0x58,0x14,11)
    f.present=true;f.host:tick()
    local log=table.concat(f.logs,'\n')
    assert(f.host.aimed==1 and not f.host.disabled,log)
    assert(log:find('ping_queue;targets=524,522;count=2',1,true),log)
    assert(log:find(';target=522;reason=REMEMBERED_PING;',1,true),log)
    assert(log:find(';selected_mark=522;selected_mark_index=2',1,true),log)
end)
print('RESULT '..passed..' passed; 0 failed (newest-first mark history and Windows native selection)')
